// CHUNK-03 § 2.9 + § 8 — generated README for the workspace `.deliveryos/`
// directory. Pure function. Written once by `deliveryos.project.create`
// when the project is first created.

export function renderDeliveryosReadme(projectName: string): string {
  const isoTimestamp = new Date().toISOString();
  return `# .deliveryos/

This directory is DeliveryOS's project memory. It is intended to be **committed to git** — it is the audit trail your release evidence is built from.

## What's here

- \`memory.sqlite\` — the index. A small SQLite DB written by the DeliveryOS extension via \`sql.js\` (no native modules).
  *Binary. Some teams prefer to gitignore this and rely on the markdown bodies + DeliveryOS's regenerate command (deferred).*
- \`memory/\` — markdown bodies, one file per memory entry, organised by type:
  - \`intent/\` — what you originally wanted
  - \`requirement/\` — what the system agreed to build
  - \`design/\` — how it should be built
  - \`codebase/\` — what already exists
  - \`execution/\` — what the coding harness was asked to do
  - \`result/\` — what actually happened
  - \`verification/\` — whether the work passed
  - \`release/\` — what was released and why
  - \`test-spec/\` — the executable verification contract for a requirement

See \`docs/architecture/memory-layers.md\` in the DeliveryOS repo for the canonical typology.

## What's NOT here

- \`.deliveryos-handoff/\` lives in your workspace root (sibling to \`.deliveryos/\`). That's the harness-facing churn directory — DeliveryOS writes briefs into it for Claude Code or Codex to read. See the DeliveryOS docs.

## Editing

The markdown bodies are safe to edit by hand — DeliveryOS will pick up your edits next time it reads. The \`memory.sqlite\` is regenerated by DeliveryOS; manual edits to it are not preserved.

Project: **${projectName}**
Created: **${isoTimestamp}**
`;
}
