// L2 — aggregate markdown views for the post-build iteration loop.
//
// The SQLite memory store is the source of truth; per-entry markdown bodies
// already mirror each bug/CR. This module adds the human-facing *aggregate*
// tables — `.deliveryos/DEFECT_LIST.md` and `.deliveryos/CHANGE_REQUESTS.md` —
// regenerated from the store on every bug/CR mutation. The format mirrors the
// ad-hoc DEFECT_LIST.md the user hand-rolled while dogfooding edgenta_OKR, so
// terminal agents and git diffs see a familiar, frictionless table.
//
// Rendering is pure (view-model in, markdown out) so it is fully unit-testable
// without a filesystem. The write helpers resolve view-models from the store
// and persist via the workspace FS.

import * as vscode from 'vscode';
import type { BugRecord, ChangeRequestRecord, MemoryStore } from '../memory/MemoryStore';
import { deliveryosDir } from '../memory/paths';

const UTF8 = new TextEncoder();

export const DEFECT_LIST_FILENAME = 'DEFECT_LIST.md';
export const CHANGE_REQUESTS_FILENAME = 'CHANGE_REQUESTS.md';

// --- Defect (bug) table ---------------------------------------------------

export interface DefectRow {
  readonly id: string; // BUG-NNN
  readonly severity: string;
  readonly status: string;
  readonly area: string;
  readonly description: string;
  readonly discoveredIn: string;
  readonly requirement: string; // REQ-NNN or '—'
  readonly verified: string; // YYYY-MM-DD or '—'
  readonly notes: string;
}

const DEFECT_HEADER = [
  'Bug',
  'Severity',
  'Status',
  'Area',
  'Description',
  'Discovered In',
  'Requirement',
  'Verified',
  'Notes',
];

/** Render the aggregate defect table. Pure — no FS, no store. */
export function renderDefectList(rows: readonly DefectRow[]): string {
  const lines: string[] = [
    '# Defect List',
    '',
    '> Generated by DeliveryOS from the project memory store. Source of truth is',
    '> `.deliveryos/memory.sqlite`; this table is a regenerated view. Statuses:',
    '> `open → assigned → fixed → verified` (`deferred` = parked).',
    '',
  ];
  lines.push(renderTable(DEFECT_HEADER, rows.map((r) => [
    r.id,
    r.severity,
    r.status,
    r.area,
    r.description,
    r.discoveredIn,
    r.requirement,
    r.verified,
    r.notes,
  ])));
  if (rows.length === 0) {
    lines.push('', '_No defects logged yet._');
  }
  lines.push('');
  return lines.join('\n');
}

// --- Change-request table -------------------------------------------------

export interface ChangeRow {
  readonly id: string; // CR-NNN
  readonly status: string;
  readonly description: string;
  readonly added: string;
  readonly edited: string;
  readonly deleted: string;
}

const CHANGE_HEADER = ['Change', 'Status', 'Description', '+Added', '~Edited', '-Deleted'];

/** Render the aggregate change-request table. Pure — no FS, no store. */
export function renderChangeRequestList(rows: readonly ChangeRow[]): string {
  const lines: string[] = [
    '# Change Requests',
    '',
    '> Generated by DeliveryOS from the project memory store. Statuses:',
    '> `logged → prompted → applied → verified`.',
    '',
  ];
  lines.push(renderTable(CHANGE_HEADER, rows.map((r) => [
    r.id,
    r.status,
    r.description,
    r.added,
    r.edited,
    r.deleted,
  ])));
  if (rows.length === 0) {
    lines.push('', '_No change requests logged yet._');
  }
  lines.push('');
  return lines.join('\n');
}

// --- Shared table renderer ------------------------------------------------

function renderTable(header: readonly string[], rows: readonly (readonly string[])[]): string {
  const head = `| ${header.join(' | ')} |`;
  const sep = `| ${header.map(() => '---').join(' | ')} |`;
  const body = rows.map((cells) => `| ${cells.map(cell).join(' | ')} |`);
  return [head, sep, ...body].join('\n');
}

/** Escape a value for safe inclusion in a single markdown table cell. */
function cell(value: string): string {
  return (value ?? '')
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|')
    .trim();
}

/** Format a ms-epoch timestamp as YYYY-MM-DD, or '—' when absent. */
export function formatDate(ms: number | undefined): string {
  if (!ms || !Number.isFinite(ms)) return '—';
  return new Date(ms).toISOString().slice(0, 10);
}

// --- Store → view-model resolvers -----------------------------------------

/**
 * Build defect rows from bug records, resolving each `targetRequirementId`
 * (an entryId) to its REQ-NNN user id via the store.
 */
export async function defectRowsFromBugs(
  store: MemoryStore,
  bugs: readonly BugRecord[],
): Promise<DefectRow[]> {
  const rows: DefectRow[] = [];
  for (const b of bugs) {
    let requirement = '—';
    if (b.payload.targetRequirementId) {
      const req = await store.read(b.payload.targetRequirementId);
      const userId = req && (req.payload as { id?: string }).id;
      requirement = typeof userId === 'string' ? userId : b.payload.targetRequirementId;
    }
    rows.push({
      id: b.payload.id,
      severity: b.payload.severity,
      status: b.payload.status,
      area: b.payload.area ?? '—',
      description: b.payload.description,
      discoveredIn: b.payload.discoveredIn ?? '—',
      requirement,
      verified: formatDate(b.payload.verifiedAt),
      notes: b.payload.notes ?? '',
    });
  }
  return rows;
}

export function changeRowsFromCrs(crs: readonly ChangeRequestRecord[]): ChangeRow[] {
  return crs.map((c) => ({
    id: c.payload.id,
    status: c.payload.status,
    description: c.payload.description,
    added: String(c.payload.addedRequirementIds?.length ?? 0),
    edited: String(c.payload.editedRequirementIds?.length ?? 0),
    deleted: String(c.payload.deletedRequirementUserIds?.length ?? 0),
  }));
}

// --- FS writers -----------------------------------------------------------

async function writeFile(workspace: vscode.Uri, filename: string, content: string): Promise<void> {
  const dir = deliveryosDir(workspace);
  await vscode.workspace.fs.createDirectory(dir);
  const uri = vscode.Uri.joinPath(dir, filename);
  await vscode.workspace.fs.writeFile(uri, UTF8.encode(content));
}

/** Regenerate `.deliveryos/DEFECT_LIST.md` from the store for one project. */
export async function regenerateDefectList(
  workspace: vscode.Uri,
  store: MemoryStore,
  projectId: string,
): Promise<void> {
  const bugs = await store.listBugs(projectId);
  const rows = await defectRowsFromBugs(store, bugs);
  await writeFile(workspace, DEFECT_LIST_FILENAME, renderDefectList(rows));
}

/** Regenerate `.deliveryos/CHANGE_REQUESTS.md` from the store for one project. */
export async function regenerateChangeRequestList(
  workspace: vscode.Uri,
  store: MemoryStore,
  projectId: string,
): Promise<void> {
  const crs = await store.listChangeRequests(projectId);
  await writeFile(workspace, CHANGE_REQUESTS_FILENAME, renderChangeRequestList(changeRowsFromCrs(crs)));
}
